-- =========================================================
-- E-COMMERCE CLICKSTREAM ANALYTICS DATABASE SCHEMA
-- =========================================================

-- ---------------------------------------------------------
-- RAW CLICKSTREAM EVENTS
-- Stores all incoming user activity events
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS clickstream_events (
    event_id BIGSERIAL PRIMARY KEY,

    user_id VARCHAR(50) NOT NULL,
    session_id UUID NOT NULL,

    product_id VARCHAR(100) NOT NULL,

    event_type VARCHAR(20) NOT NULL
        CHECK (event_type IN ('view', 'add_to_cart', 'purchase')),

    device_type VARCHAR(20),

    location VARCHAR(100),

    event_timestamp TIMESTAMP NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------
-- INDEXES FOR FASTER ANALYTICS
-- ---------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_clickstream_product
ON clickstream_events(product_id);

CREATE INDEX IF NOT EXISTS idx_clickstream_event_type
ON clickstream_events(event_type);

CREATE INDEX IF NOT EXISTS idx_clickstream_timestamp
ON clickstream_events(event_timestamp);

CREATE INDEX IF NOT EXISTS idx_clickstream_user
ON clickstream_events(user_id);

-- ---------------------------------------------------------
-- FLASH SALE ALERTS
-- Triggered when:
-- views > 100 AND purchases < 5
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS flash_sale_alerts (
    alert_id BIGSERIAL PRIMARY KEY,

    product_id VARCHAR(100) NOT NULL,

    total_views INTEGER NOT NULL,

    total_purchases INTEGER NOT NULL,

    conversion_rate NUMERIC(10,2),

    alert_message TEXT NOT NULL,

    window_start TIMESTAMP NOT NULL,

    window_end TIMESTAMP NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_flash_sale_product
ON flash_sale_alerts(product_id);

-- ---------------------------------------------------------
-- DAILY USER SEGMENTATION
-- Generated by Airflow batch jobs
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS user_segmentation (
    segmentation_id BIGSERIAL PRIMARY KEY,

    user_id VARCHAR(50) NOT NULL,

    total_views INTEGER DEFAULT 0,

    total_add_to_cart INTEGER DEFAULT 0,

    total_purchases INTEGER DEFAULT 0,

    user_segment VARCHAR(50) NOT NULL,

    segmentation_date DATE NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_segmentation_user
ON user_segmentation(user_id);

CREATE INDEX IF NOT EXISTS idx_user_segmentation_date
ON user_segmentation(segmentation_date);

-- ---------------------------------------------------------
-- DAILY PRODUCT ANALYTICS
-- Used for reports/dashboard generation
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS daily_product_metrics (
    metric_id BIGSERIAL PRIMARY KEY,

    product_id VARCHAR(100) NOT NULL,

    metric_date DATE NOT NULL,

    total_views INTEGER DEFAULT 0,

    total_add_to_cart INTEGER DEFAULT 0,

    total_purchases INTEGER DEFAULT 0,

    conversion_rate NUMERIC(10,2),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_daily_metrics_product
ON daily_product_metrics(product_id);

CREATE INDEX IF NOT EXISTS idx_daily_metrics_date
ON daily_product_metrics(metric_date);

-- ---------------------------------------------------------
-- OPTIONAL MATERIALIZED VIEW
-- Fast analytics querying
-- ---------------------------------------------------------

CREATE MATERIALIZED VIEW IF NOT EXISTS product_conversion_summary AS
SELECT
    product_id,

    COUNT(*) FILTER (WHERE event_type = 'view') AS total_views,

    COUNT(*) FILTER (WHERE event_type = 'purchase') AS total_purchases,

    ROUND(
        (
            COUNT(*) FILTER (WHERE event_type = 'purchase')::NUMERIC
            /
            NULLIF(
                COUNT(*) FILTER (WHERE event_type = 'view'),
                0
            )
        ) * 100,
        2
    ) AS conversion_rate

FROM clickstream_events
GROUP BY product_id;

-- =========================================================
-- SAMPLE COMMENT
-- =========================================================

COMMENT ON TABLE clickstream_events IS
'Stores all real-time clickstream events from Kafka producer';

COMMENT ON TABLE flash_sale_alerts IS
'Stores products with high interest but low conversion';

COMMENT ON TABLE user_segmentation IS
'Stores daily user segmentation results generated by Airflow';

COMMENT ON TABLE daily_product_metrics IS
'Stores aggregated daily analytics metrics';